apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-test-pvc
spec:
  accessModes:
    - ReadWriteOnce  # 块存储支持单节点读写
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi