apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeout
  namespace: study-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    # 🔥 官方WebSocket专用注解，100%替代snippet，无权限问题
    nginx.ingress.kubernetes.io/websocket-services: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: ws.test.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx
            port:
              number: 80