apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-cm
  namespace: default
  labels:
    app: nginx-test-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-cm
  template:
    metadata:
      labels:
        app: nginx-test-cm
    spec:
      volumes:
      - name: nginxconfsecret #卷名字
        secret:  #使用secret类型的卷
          secretName: nginxconf  #secret的名字，必须和上面创建的secret名字一致
      containers:
      - name: nginx-test-cm
        image: registry.cn-beijing.aliyuncs.com/dotbalo/nginx:1.15.12
        volumeMounts:
        - name: nginxconfsecret  #卷名字，必须和上面定义的卷名字一致
          mountPath: /mnt  #  挂载到容器里面的路径，必须是目录路径，不能是文件路径