apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.cn-beijing.aliyuncs.com/dotbalo/nginx:1.15.12
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /opt
          name: share-volume
      - name: redis
        image: registry.cn-beijing.aliyuncs.com/dotbalo/redis:7.2.5
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mnt  # 挂载路径
          name: share-volume  # 卷名称
        - mountPath: /data  # 挂载路径
          name: data  # 卷名称
      volumes:
      - name: share-volume # 卷名称
        emptyDir:  # 使用 emptyDir 卷类型，表示在 Pod 生命周期内创建一个临时目录，Pod 删除后数据会丢失、
          medium: Memory  # 可选项，表示将 emptyDir 卷存储在内存中（tmpfs），默认是存储在节点的磁盘上
          sizeLimit: 10Mi  # 可选项，表示 emptyDir 卷的最大容量限制，单位可以是 Mi、Gi 等，如果超过限制，Pod 会被杀死并重启。默认没有限制。
      - name: data  # 卷名称
        hostPath:   # 使用 hostPath 卷类型，表示将节点上的一个目录挂载到 Pod 中
          path: /data   # 节点上的目录路径，必须是绝对路径